name: vermay
version: 0.1.1
description: >
  Official Dart implementation of Version (Version Management Format for Articles withby YAML front-matter Markdown), a lightweight binary diff format and versioning system for content files, designed for custom CMS integration.
author: Haruka Sato <as.he.that.doth.serve@gmail.com>
homepage: https://www.thinking-grp.org/project/thinkCMS#Vermay
documentation: https://www.thinking-grp.org/project/thinkCMS#Vermay
repository: https://github.com/thinking-grp/Vermay
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  yaml: ^3.1.3
  markdown: ^7.3.0
  pointycastle: ^4.0.0
  crclib: ^3.0.0
  adler32: ^2.0.0
topics:
  - vermay
  - diff
  - versioning
  - binary-format
  - checksum
  - cms
  - metadata
  - content-management
  - revision
  - file-format
  - data-integrity
